tacotron2 번역
PyTorchKorea/hub-kr pull request #102
Opened 2022-09-11 13:39 UTC by cpprhtn

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

tacotron2 모델 번역

2022-09-14 11:44 UTC, Woodywarhol9 reviewed
번역 잘 해주셨네요!
몇 가지 수정 사항 제안 드려요~

2022-09-14 11:44 UTC, Woodywarhol9 commented on nvidia_deeplearningexamples_tacotron2.md
> +Tacotron 2 및 WaveGlow 모델은 추가 운율 정보 없이 원본 텍스트에서 자연스러운 음성을 합성할 수 있는 텍스트 음성 변환 시스템을 형성합니다. Tacotron 2 모델은 인코더-디코더 아키텍처를 사용하여 입력 텍스트에서 멜 스펙트로그램을 생성합니다. WaveGlow (torch.hub를 통해서도 사용 가능)는 멜 스펙트로그램을 사용하여 음성
`흐름 기반`은 `흐름 기반(flow-based)`처럼 영어를 함께 적어주면 이해하기 더 쉬울 거 같아요!

2022-09-14 11:44 UTC, Woodywarhol9 commented on nvidia_deeplearningexamples_tacotron2.md
> +Tacotron 2 모델의 구현은 본 논문에서 설명한 모델과 다릅니다. 여기서 제공하는 모델에서는 LSTM 레이어를 정규화하기 위해 Zoneout 대신 Dropout을 사용합니다.
`모델의 구현`이랑 `여기서 제공하는 모델` 이 결국 hub에서 사용 가능한 사전 훈련된 모델이니까 요런 식으로 언급해주면 더 좋을 거 같아요!

`사전 훈련된 Tacotron 2 모델은 논문과 다르게 구현됐습니다.  ~~~`

2022-09-14 11:44 UTC, Woodywarhol9 commented on nvidia_deeplearningexamples_tacotron2.md
> +파일에 작성하여 들어볼 수 있습니다.
`파일로 저장하여 들어볼 수 있습니다.`라고 번역하면 어떨까요??

2022-09-14 11:57 UTC, cpprhtn commented on nvidia_deeplearningexamples_tacotron2.md
> +Tacotron 2 모델의 구현은 본 논문에서 설명한 모델과 다릅니다. 여기서 제공하는 모델에서는 LSTM 레이어를 정규화하기 위해 Zoneout 대신 Dropout을 사용합니다.
훨씬 매끄러운 문장이 된것 같습니다!

2022-09-14 11:57 UTC, cpprhtn commented on nvidia_deeplearningexamples_tacotron2.md
> +파일에 작성하여 들어볼 수 있습니다.
좋은것 같습니다 :)

2022-09-14 11:57 UTC, cpprhtn commented on nvidia_deeplearningexamples_tacotron2.md
> +Tacotron 2 및 WaveGlow 모델은 추가 운율 정보 없이 원본 텍스트에서 자연스러운 음성을 합성할 수 있는 텍스트 음성 변환 시스템을 형성합니다. Tacotron 2 모델은 인코더-디코더 아키텍처를 사용하여 입력 텍스트에서 멜 스펙트로그램을 생성합니다. WaveGlow (torch.hub를 통해서도 사용 가능)는 멜 스펙트로그램을 사용하여 음성
👍

2022-09-14 14:44 UTC, FollowerOfScriabin approved these changes
좋은 번역입니다.

2023-04-02 15:20 UTC, hyoyoung requested changes
오류를 지적하는것이 아닌 제안입니다.
원래 안이 더 괜찮다면 답글을 달아주세요.

2023-04-02 15:20 UTC, hyoyoung commented on nvidia_deeplearningexamples_tacotron2.md
> +Tacotron 2 및 WaveGlow 모델은 추가 운율 정보 없이 원본 텍스트에서 자연스러운 음성을 합성할 수 있는 텍스트 음성 변환 시스템을 형성합니다. Tacotron 2 모델은 인코더-디코더 아키텍처를 사용하여 입력 텍스트에서 멜 스펙트로그램을 생성합니다. WaveGlow (torch.hub를 통해서도 사용 가능)는 멜 스펙트로그램을 사용하여 음성
이 부분은 오류 수정이 아닌 제안인데,
'형성합니다'는 model form를 번역한거 같은데, 조금 어려운 단어 선택인듯합니다
'만듭니다'는 어떨까요?

Tacotron 2 및 WaveGlow 모델은 추가 운율 정보 없이 별도 처리가 안된 글로 자연스러운 음성을 합성할 수 있는 텍스트 음성 변환 시스템을 만듭니다.

2023-04-02 15:20 UTC, hyoyoung commented on nvidia_deeplearningexamples_tacotron2.md
> +Tacotron 2 및 WaveGlow 모델은 추가 운율 정보 없이 원본 텍스트에서 자연스러운 음성을 합성할 수 있는 텍스트 음성 변환 시스템을 형성합니다. Tacotron 2 모델은 인코더-디코더 아키텍처를 사용하여 입력 텍스트에서 멜 스펙트로그램을 생성합니다. WaveGlow (torch.hub를 통해서도 사용 가능)는 멜 스펙트로그램을 사용하여 음성
멜 스펙트로그램은 맨처음엔 원어를 병기하는건 어떨까요?
멜 스펙트로그램(mel spectrogram)

2023-04-02 15:20 UTC, hyoyoung commented on nvidia_deeplearningexamples_tacotron2.md
> +- 사전 훈련된 Tacotron2 및 Waveglow 모델은 torch.hub에서 로드됩니다.
torch.hub에서 로드됩니다.
->
torch.hub에서 가져옵니다.

이건 어떨까요?

2023-04-02 16:25 UTC, cpprhtn commented on nvidia_deeplearningexamples_tacotron2.md
> +- 사전 훈련된 Tacotron2 및 Waveglow 모델은 torch.hub에서 로드됩니다.
제안주시는 사안들이 더 좋은 문장을 만드는것 같습니다 👍

2023-04-02 17:17 UTC, hyoyoung approved these changes
good

2023-04-02 17:17 UTC, merged