IBN-Net 번역
PyTorchKorea/hub-kr pull request #106
Opened 2022-09-12 05:44 UTC by cpprhtn

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #105 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

IBN-Net 번역

2022-09-12 12:21 UTC, euroversedev reviewed
연휴에도 대단하십니다! 보행자 재식별 프로젝트를 계획 중인데, 덕분에 IBN-Net에 대해 알게되었네요👍 
![FriendsGIF](https://user-images.githubusercontent.com/98439882/189652122-f9973b30-70f9-40b1-a835-b1dd69902703.gif)

2022-09-12 12:21 UTC, euroversedev commented on pytorch_vision_ibnnet.md
> +# Imagnet의 1000개 클래스에 대한 신뢰도 점수를 가진 1000 형태의 텐서 출력
용어 사용 규칙에서 Tensor에 대해 '번역하지 않음'으로 규정되어 있어서 수정하면 좋을 것 같습니다 😄

2022-09-12 13:24 UTC, cpprhtn commented on pytorch_vision_ibnnet.md
> +# Imagnet의 1000개 클래스에 대한 신뢰도 점수를 가진 1000 형태의 텐서 출력
엇 수정하겠습니다 감사합니다

2022-09-14 02:40 UTC, HyunKyungHan requested changes
깔끔한 번역인 것 같습니다!
고생하셨습니다 :)

2022-09-14 02:40 UTC, HyunKyungHan commented on pytorch_vision_ibnnet.md
> +사전 훈련된 모델이 있는 ImageNet 데이터셋의 정확도는 아래에 나열되어 있습니다.
아래 표는 모델의 정확도를 나타내는 것이니까,
`ImageNet 데이터셋을 사용했을 때 사전 훈련된 모델들의 정확도는 다음과 같습니다.` 와 같이 번역하는 것이 좋을 것 같습니다!

2022-09-14 02:40 UTC, HyunKyungHan commented on pytorch_vision_ibnnet.md
> +두 가지 Re-ID 벤치마크 Market1501 및 DukeMTMC-reID에 대한 rank1/mAP는 아래에 나열되어 있습니다([michuanhaohao/reid-strong-baseline](https://github.com/michuanhaohao/reid-strong-baseline)에서 가져옴).
다른 문장들과의 통일성을 위해 `가져옴` -> `가져왔습니다`라고 쓰거나 
`출처:[michuanhaohao/reid-strong-baseline](https://github.com/michuanhaohao/reid-strong-baseline)`로 쓰는 건 어떨까요?

2022-09-14 07:30 UTC, cpprhtn commented on pytorch_vision_ibnnet.md
> +두 가지 Re-ID 벤치마크 Market1501 및 DukeMTMC-reID에 대한 rank1/mAP는 아래에 나열되어 있습니다([michuanhaohao/reid-strong-baseline](https://github.com/michuanhaohao/reid-strong-baseline)에서 가져옴).
저도 처음에 출처라고 의역할까 고민했었는데, 수정하는게 맞는거 같습니다!.. 반영하겠습니당 :)

2022-09-14 07:31 UTC, cpprhtn commented on pytorch_vision_ibnnet.md
> +사전 훈련된 모델이 있는 ImageNet 데이터셋의 정확도는 아래에 나열되어 있습니다.
깔끔한 문장 추천 감사합니다.

2022-09-14 11:58 UTC, Taeyoung96 reviewed
번역하시느라 고생 많으셨습니다.  
몇 가지 의견 남겨봅니다.

2022-09-14 11:58 UTC, Taeyoung96 commented on pytorch_vision_ibnnet.md
> +# Imagnet의 1000개 클래스에 대한 신뢰도 점수를 가진 1000 형태의 Tensor 출력
오타인 것 같네요. ImageNet으로 바꿔야 할 것 같습니다.

2022-09-14 11:58 UTC, Taeyoung96 commented on pytorch_vision_ibnnet.md
> +style transfer에 동기를 부여받은 IBN-Net은 단일 심층 네트워크에서 인스턴스 정규화와 일괄 정규화를 신중하게 통합합니다.
`동기를 부여받은`보다  
`Style transfer에 영감을 얻어`라는 의역은 어떠실까요?

2022-09-14 12:01 UTC, cpprhtn commented on pytorch_vision_ibnnet.md
> +# Imagnet의 1000개 클래스에 대한 신뢰도 점수를 가진 1000 형태의 Tensor 출력
감사합니다 :)

2022-09-14 12:02 UTC, cpprhtn commented on pytorch_vision_ibnnet.md
> +style transfer에 동기를 부여받은 IBN-Net은 단일 심층 네트워크에서 인스턴스 정규화와 일괄 정규화를 신중하게 통합합니다.
훨씬 문장이 매끄러워진것 같습니다! LGTM 👍 👍 👍

2022-09-15 10:05 UTC, Taeyoung96 approved these changes
리뷰사항 반영 확인했습니다. 번역 하시느라 고생하셨습니다. :smile:

2023-04-02 15:27 UTC, hyoyoung approved these changes
good

2023-04-02 15:27 UTC, merged