ResNeSt 번역
PyTorchKorea/hub-kr pull request #110
Opened 2022-09-30 07:45 UTC by cpprhtn

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #107 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

ResNeSt 번역

2023-04-02 15:35 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다
몇가지 사항 확인 부탁드립니다

2023-04-02 15:35 UTC, hyoyoung commented on pytorch_vision_resnest.md
> +최근 이미지 분류 모델이 계속 발전하고 있지만 객체 감지 및 의미 분할과 같은 대부분의 다운스트림 애플리케이션(downstream applications)은 간단하게 모듈화된 구조로 인해 여전히 ResNet 변형을 백본 네트워크로 사용합니다. 기능 맵 그룹 전반에 걸쳐 주의를 기울일 수 있는 Split-Attention 블록을 제시합니다. 이러한 Spli
백본 네트워크와 인스턴스 분할에는 영어 병기를 해두는것이 좋을 것 같습니다

2023-04-02 15:35 UTC, hyoyoung commented on pytorch_vision_resnest.md
> +# 예시로 ResNeSt-50을 사용하여 사전 훈련된 모델을 불러오기
아주 사소한건데 load는 불러오기로도 많이 쓰이는데, 위에서 get에 불러오기로 썼으니
이번 load에는 가져오기로 바꾸는건 혹시 어떨까요?

2023-04-03 04:54 UTC, cpprhtn commented on pytorch_vision_resnest.md
> +# 예시로 ResNeSt-50을 사용하여 사전 훈련된 모델을 불러오기
감사합니다

2023-04-03 11:46 UTC, merged