Wide ResNet 번역
PyTorchKorea/hub-kr pull request #112
Opened 2022-10-07 11:39 UTC by cpprhtn

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

2022-10-07 15:44 UTC, HyunKyungHan requested changes
번역 수고하셨습니다!
꾸준히 번역 pr 올리는 거 대단하세요...👍🏻
저도 issue 남겨둔 것 곧 pr 해야겠네요!

2022-10-07 15:44 UTC, HyunKyungHan commented on pytorch_vision_wide_resnet.md
> +그렇지 않으면 아키텍처가 동일합니다.
'그렇지 않으면'을 의역하면 의미 전달에 더 도움이 될 것 같은데, 다음과 같이 번역하는 건 어떨까요?

```suggestion
이외의 아키텍처는 ResNet과 동일합니다. 
```

2022-10-07 15:44 UTC, HyunKyungHan commented on pytorch_vision_wide_resnet.md
> +`wide_resnet50_2` 및 `wide_resnet101_2` 모델은 [Warm Restarts가 있는 SGD(SGDR)](https://arxiv.org/abs/1608.03983)를 사용하여 혼합 정밀도(Mixed Precision) 방식으로 FP16에서 학습되었습니다.
mixed precision은 FP16과 FP32를 함께 사용하는 것으로 알고 있는데, 원문 자체가 조금 모호하게 쓰인 것 같네요...
FP16에 대한 언급을 아예 하지 않는 것은 어떨까요?
(혹시 제가 잘못 알고 있는 거라면 지적 부탁드립니다 🥲)

```suggestion
`wide_resnet50_2` 및 `wide_resnet101_2` 모델은 [Warm Restarts가 있는 SGD(SGDR)](https://arxiv.org/abs/1608.03983)를 사용하여 혼합 정밀도(Mixed Precision) 방식으로 학습되었습니다.
```

2022-10-07 16:59 UTC, cpprhtn commented on pytorch_vision_wide_resnet.md
> +`wide_resnet50_2` 및 `wide_resnet101_2` 모델은 [Warm Restarts가 있는 SGD(SGDR)](https://arxiv.org/abs/1608.03983)를 사용하여 혼합 정밀도(Mixed Precision) 방식으로 FP16에서 학습되었습니다.
좋은 의견 감사합니다!!!!

2023-04-02 15:38 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다

한가지 사항 확인 부탁드립니다

2023-04-02 15:38 UTC, hyoyoung commented on pytorch_vision_wide_resnet.md
> +병목(bottleneck) 블록이 있는 심층 ImageNet 모델은 내부 3x3 컨볼루션의 채널 수를 증가 시켰습니다.
convolution은 보통 합성곱이라고 문서에 번역하고 있습니다
컨볼루션으로 한건 혹시 강조의 의미일까요?

2023-04-03 04:55 UTC, cpprhtn commented on pytorch_vision_wide_resnet.md
> +병목(bottleneck) 블록이 있는 심층 ImageNet 모델은 내부 3x3 컨볼루션의 채널 수를 증가 시켰습니다.
통일성을 위해서 합성곱으로 수정하도록 하겠습니다

2023-04-03 11:46 UTC, hyoyoung approved these changes
good

2023-04-03 11:47 UTC, merged