silero_stt 번역
PyTorchKorea/hub-kr pull request #114
Opened 2022-10-29 02:53 UTC by cpprhtn

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #113 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

2023-04-02 15:50 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다

몇가지 사항 확인 부탁드립니다.

2023-04-02 15:50 UTC, hyoyoung commented on snakers4_silero-models_stt.md
> + read_audio, prepare_model_input) = utils  # 자세한 내용은 함수 서명을 참조하세요.
signature는 번역 안하는게 더 자연스럽지 않을까요?
자세한 내용은 함수 시그니처(function signature)를 참조하세요.

이건 단순히 취향의 문제긴 합니다. 원하는게 맞다면 답글을 주세요.

2023-04-02 15:50 UTC, hyoyoung commented on snakers4_silero-models_stt.md
> -For additional examples and other model formats please visit this [link](https://github.com/snakers4/silero-models). For quality and performance benchmarks please see the [wiki](https://github.com/sn
이러한 리소스는 수시로 업데이트됩니다.

->

관련 자료는 수시로 업데이트됩니다.

2023-04-03 05:02 UTC, cpprhtn commented on snakers4_silero-models_stt.md
> + read_audio, prepare_model_input) = utils  # 자세한 내용은 함수 서명을 참조하세요.
이부분은 당시에 번역할때 저도 멈칫했던 부분이긴 하였습니다.
function signature라는 용어자체를 저는 처음 접해 봤어서 서명이라 번역하는게 맞는지 몰랐었는데, 차라리 영어 그대로 표현하는것이 맞을것같네요

2023-04-03 11:58 UTC, hyoyoung requested changes
몇가지 사항 확인 부탁드립니다

2023-04-03 11:58 UTC, hyoyoung commented on snakers4_silero-models_stt.md
> -We hope that our efforts with Open-STT and Silero Models will bring the ImageNet moment in speech closer.
해당 줄의 번역이 빠져있습니다

2023-04-03 11:58 UTC, hyoyoung commented on snakers4_silero-models_stt.md
> +Silero Speech-To-Text 모델은 일반적으로 사용되는 여러 언어에 대해 소형 폼 팩터 형태로 엔터프라이즈급 STT를 제공합니다. 기존 ASR 모델과 달리 다양한 방언, 코덱, 도메인, 노이즈, 낮은 샘플링 속도에 강인합니다(단순화를 위해 오디오는 16kHz로 다시 샘플링해야 함). 모델은 샘플 형태의 정규화된 오디오(즉, [-1, 1] 범위로
마지막 문장이 어려워서 번역을 조금 바꾸는건 어떨까요?

단순화를 위해 디코더 도구를 제공합니다.
모델 자체에 포함할 수 있지만 자막이 결합된 모듈은,
특정한 내보내기 상황에서 레이블같은 모델의 생성물을 저장할 때 문제가 있었습니다.

문장 자체가 길어서
We provide a decoder utility for simplicity
(we could include it into our model itself,
but scripted modules had problems with storing model artifacts i.e. labels during certain export scenarios)
3개로 쪼개서 바꿔보았습니다.

2023-04-03 13:07 UTC, cpprhtn commented on snakers4_silero-models_stt.md
> -We hope that our efforts with Open-STT and Silero Models will bring the ImageNet moment in speech closer.
해당줄은 번역해서 넣기도 애매하고 없어도 좋을것 같다고 판단해서 빼게 되었는데 혹시 없어도 괜찮지 않으려나요?

2023-04-03 13:08 UTC, cpprhtn commented on snakers4_silero-models_stt.md
> +Silero Speech-To-Text 모델은 일반적으로 사용되는 여러 언어에 대해 소형 폼 팩터 형태로 엔터프라이즈급 STT를 제공합니다. 기존 ASR 모델과 달리 다양한 방언, 코덱, 도메인, 노이즈, 낮은 샘플링 속도에 강인합니다(단순화를 위해 오디오는 16kHz로 다시 샘플링해야 함). 모델은 샘플 형태의 정규화된 오디오(즉, [-1, 1] 범위로
감사합니다 👍

2023-04-03 14:06 UTC, hyoyoung commented on snakers4_silero-models_stt.md
> -We hope that our efforts with Open-STT and Silero Models will bring the ImageNet moment in speech closer.
애매하긴한데, 아직은 speech에 ImageNet 같은 순간이 오지 않았다는것도 정보이니 넣는게 조금 더 나을거 같습니다

2023-04-03 14:30 UTC, cpprhtn commented on snakers4_silero-models_stt.md
> -We hope that our efforts with Open-STT and Silero Models will bring the ImageNet moment in speech closer.
> Speech에서 Open-STT와 Silero Models에 대한 노력이 ImageNet 같은 순간에 다가가길 바란다.

본문을 기반으로 위와 같이 번역해봤는데 피드백 부탁드립니다 :)

2023-04-04 02:25 UTC, hyoyoung approved these changes
good

2023-04-04 02:25 UTC, merged