Translate pytorch_vision_resnext.md
PyTorchKorea/hub-kr pull request #15
Opened 2021-11-07 07:17 UTC by joonkeekim

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #14 (숫자)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

pytorch_vision_resnext.md 문서를 번역하였습니다.

2021-11-07 11:48 UTC, des00 commented on pytorch_vision_resnext.md
>  ### Model Description
여기랑 아래의 Resource도 번역하는게 어떨까 싶습니다.
기존에 번역 올려두신 분도 이쪽 부분 다 번역하셨더라고요.
https://github.com/9bow/PyTorch-hub-kr/pull/12/files

2021-11-11 08:47 UTC, Taeyoung96 reviewed
고생하셨습니다!

2021-11-11 08:47 UTC, Taeyoung96 commented on pytorch_vision_resnext.md
> +사전 훈련된 모든 모델들은 입력 이미지들이 같은 방식으로 정규화된것으로 생각합니다.
맞춤법상,  
'정규화 된 것으로'라고 바꿔야 할 것 같습니다!

2021-11-11 08:47 UTC, Taeyoung96 commented on pytorch_vision_resnext.md
> +이미지는 `[0, 1]` 범위로 로드한 다음 `mean = [0.485, 0.456, 0.406]` 과 `std = [0.229, 0.224, 0.225]`
이미지는 `[0, 1]` 범위 로드한 다음 >> 이미지는 `[0,1]` 범위로 불러온 다음  
이라고 바꾸는 건 혹시 어떨까요?

2022-04-11 10:05 UTC, Taeyoung96 commented
@joonkeekim   
안녕하세요.  Feedback에 대한 추가적인 수정 및 comment를 남겨주시면 감사하겠습니다!

2022-04-11 11:41 UTC, 9bow requested changes
@joonkeekim 님, 위 @Taeyoung96 님의 덧글 확인 부탁드립니다. :)

2023-04-02 03:50 UTC, hyoyoung commented
마지막 피드백 이후 15일이 지나면 보통 닫게 됩니다.
진행이 많이 된 PR이므로, 마무리 피드백 처리 부탁드리겠습니다

2023-04-02 08:47 UTC, joonkeekim commented
확인이 늦어 매우 늦은 피드백 죄송합니다..! 우선적으로 말씀해주신 1. 용어 2. 추가 번역 해결하고 커밋 올렸습니다.  
하지만 이미 번역되고 Merge된 pytorch_vision_resnext.md가 있어 PR을 닫아도 괜찮을까요?

2023-04-02 14:52 UTC, hyoyoung commented
그럼 본 PR은 닫겠습니다. 수고 많으셨습니다

2023-04-02 14:52 UTC, closed without merging