Pytorch-hub-kr Window10 build 방법 설명 추가
PyTorchKorea/hub-kr pull request #25
Opened 2022-07-16 08:12 UTC by Taeyoung96

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)  
- #24 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [x] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

Window 10 빌드를 할 때 필요한 참고자료들을 첨부하였습니다.

2022-07-30 06:21 UTC, Lee-JaeWon commented
> ### 기존 문서
> Windows 10에서 make 명령어 사용
[ezwinports](https://sourceforge.net/projects/ezwinports/)를 설치해야 합니다. 아래의 참고자료를 참고하여 설치를 진행해주세요.
참고자료 : [MINGW64 "make build" error: "bash: make: command not found"](https://stackoverflow.com/questions/36770716/mingw64-make-build-error-bash-make-command-not-found)

[chocolatey 설치 및 choco 이용한 make 설치](https://jie0025.tistory.com/72)

기존 문서에서 ezwinports를 이용해 windows에서 make가 적용되지 않을 때 [위 자료](https://jie0025.tistory.com/72)를 참고해 chocolatey를 설치하고 이를 통해 make를 설치하여 사용할 수 있습니다.
- Installation
`choco install make`
- Version check
`make -v`

2022-08-07 09:50 UTC, codingbowoo requested changes
간단하게 리뷰해 보았습니다. 
덕분에 윈도우 사용자분들이 더 쉽게 기여할 수 있을 것 같습니다. 감사합니다!

2022-08-07 09:50 UTC, codingbowoo commented on Window_build.md
> +❗️ 각각 환경 설정마다 버전을 맞춰주는 것이 중요합니다!
Ruby, nodejs, yarn, make 각각의 버전을 맞추는 것이 중요하다는 말씀이 맞나요? 
서로 뭔가 디펜던시가 있는 것이지요? 

그렇다면,
환경 설정 시 각각의 버전을 아래 명시된 버전과 동일하게 설정해야 합니다. 로 문장을 바꾸는 것은 어떨까요?
 
문장을 조금 더 자연스럽게 바꿔봤습니다.

2022-08-07 09:50 UTC, codingbowoo commented on Window_build.md
> +[RubyInstaller](https://rubyinstaller.org/downloads/archives/)에서 `ruby+devkit 2.7.4-1 (x64)`를 다운 받아 설치합니다.
사소한 부분이지만, `Ruby+Devkit 2.7.4-1` 으로 완전 동일한 표기를 하면 어떨까요? 
처음 하는 사람들은 사소한 부분에서도 헤맬 수 있다고 생각해서요. 

추가) x86을 쓰시는 분이 계실 수도 있을까요?

2022-08-07 09:50 UTC, codingbowoo commented on Window_build.md
> +git bash command 창에 `gem install bundler -v 2.3.13`로 bundler를 설치해주세요.
git bash command 창에 `gem install bundler -v 2.3.13` 명령어를 실행하여 bundler를 설치해주세요. 로 바꾸면 더 자연스러울 것 같아요.

2022-08-07 09:50 UTC, codingbowoo commented on Window_build.md
> +node.js 설치는 아래의 참고자료를 참고해서 설치했습니다. 버전은 `16.13.2`입니다.
아래 링크를 참고하여 설치했습니다. 하면 어떨까요?

2022-08-07 09:50 UTC, codingbowoo commented on Window_build.md
> +- 참고자료 : [윈도우 node.js 설치하기](https://kitty-geno.tistory.com/61)
자연스럽게 여기는 
(node.js 설치 시) 참고한 링크 
로 수정하는 것도 좋을 것 같아요.

2022-08-07 09:50 UTC, codingbowoo commented on Window_build.md
> +만약 ezwinports를 이용하여 windows에서 make가 적용되지 않을 때 chocolatey를 설치하고 이를 통해 make를 설치하여 사용할 수 있습니다.
만약 ezwinports를 통해 make를 설치했음에도 불구하고 make 명령어를 사용할 수 없다면, 
chocolatey 를 설치하여 make 명령어를 사용할 수 있습니다. 
로 바꾸면 될 것 같아요

2022-08-07 14:39 UTC, Taeyoung96 commented on Window_build.md
> +❗️ 각각 환경 설정마다 버전을 맞춰주는 것이 중요합니다!
리뷰 반영했습니다!

2022-08-08 02:20 UTC, Taeyoung96 commented
@codingbowoo   
리뷰 반영하였습니다! 확인해보시고 merge 부탁드립니다 :smile:

2022-08-10 01:55 UTC, codingbowoo requested changes
한 문장만 확인 부탁드립니다~!

2022-08-10 01:55 UTC, codingbowoo commented on Window_build.md
> +❗️ 환경 설정 시 각각의 버전을 아래 명시된 버전과 동일하게 수월하게 빌드를 실행할 수 있습니다!
문장이 조금 어색한데요, 
동일하게 수월하게 빌드를 실행할 수 있습니다!   -> 동일하게 맞추어 수월하게 빌드를 진행할 수 있습니다! 
정도면 될까요...? 요거 한 문장만 수정해주시면 머지하겠습니다!

2022-08-10 05:28 UTC, Taeyoung96 commented on Window_build.md
> +❗️ 환경 설정 시 각각의 버전을 아래 명시된 버전과 동일하게 수월하게 빌드를 실행할 수 있습니다!
지금 보니까 저도 그런 것 같네요ㅠ  
꼼꼼한 리뷰 감사드립니다! :+1:

2022-08-10 05:37 UTC, codingbowoo approved these changes
LGTM! 수고 많으셨습니다 👍

2022-08-10 05:38 UTC, merged