[번역] vision_squeezenet 모델
PyTorchKorea/hub-kr pull request #32
Opened 2022-08-07 00:56 UTC by zhoonit

Signed-off-by: Jihoon Lee <zhoonit@gmail.com>

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

squeezenet 번역을 추가하였습니다.

2022-08-12 02:48 UTC, Lee-JaeWon requested changes
사소한 부분에 대해서 리뷰를 남겨보았습니다.
전체적으로 의역이 담긴 부분들이 굉장히 매끄러운 것 같습니다.👍👍

2022-08-12 02:48 UTC, Lee-JaeWon commented on pytorch_vision_squeezenet.md
> +# 예제 (torch vision 필요)
`torch vision 필요`에서 본래 [라이브러리](https://pytorch.org/vision/stable/index.html) 이름과 같이 `torchvision`으로 붙여쓰는 것이 좋지 않을까 의견을 남겨봅니다:)

2022-08-18 15:24 UTC, songhee23 commented on pytorch_vision_squeezenet.md
> +Imagenet 기준으로 훈련된 모델들의 1-crop 에러율은 아래와 같습니다.
`Imagenet 기준으로 훈련된 모델들의` 를 `Imagenet 데이터셋 기준으로 학습된 모델들의` 로 제안해 봅니다. 😃 
dataset -> 데이터셋, pretrained -> 학습된으로 해석하는 것은 용어규칙에서 참조하였습니당
용어 규칙 : https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2022-08-18 15:24 UTC, songhee23 commented on pytorch_vision_squeezenet.md
> +# 가능한 경우 model 과 input image 를 gpu 를 사용하도록 조정
for speed 해석이 빠진것 같습니다. 
`가능한 경우 속도를 위해 model과 input image를 gpu를 사용하도록 조정` 로 제안합니다 😃

2022-08-18 15:24 UTC, songhee23 commented on pytorch_vision_squeezenet.md
> +# 확률값이 가장 높은 범주 출력
per image 해석이 빠진것 같습니다. 
`이미지별 확률값이 가장 높은 범주 출력` 로 제안합니다 😃

2022-08-18 15:24 UTC, songhee23 commented on pytorch_vision_squeezenet.md
> +# 웹사이트에서 이미지 다운로드
`웹사이트에서 이미지 다운로드` 를 `pytorch 웹사이트에서 예제 이미지 다운로드` 로 제안합니다 😄

2022-08-20 02:13 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +이 때 모든 픽셀들은 0과 1 사이의 값을 가지도록 변환한 이후 `평균 = [0.485, 0.456, 0.406]`, `표준편차 = [0.229, 0.224, 0.225]` 로 정규화해야 합니다.
std 라고 적혀있는 것 보니, 원문으로 적는게 더 적절해 보입니다. 반영하였습니다 :)

2022-08-20 02:14 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +# 웹사이트에서 이미지 다운로드
적절해보이네요 :) pytorch 부분을 추가하였습니다 👍

2022-08-20 02:15 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +# 가능한 경우 model 과 input image 를 gpu 를 사용하도록 조정
다음과 같이 수정하였습니다.

`# 빠르게 실행하기 위해 가능한 경우 model 과 input image 를 gpu 를 사용하여 조정`

2022-08-20 02:16 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +# 확률값이 가장 높은 범주 출력
추가하였습니다 👍

2022-08-20 02:17 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +`squeezenet1_0` 모델은 [SqueezeNet: AlexNet-level accuracy with 50x fewer parameters and <0.5MB model size](https://arxiv.org/pdf/1602.07360.pdf) 논문의 구현입니다.
주술호응이 더 맞는 느낌이네요! 반영하였습니다~

2022-08-20 02:17 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +Imagenet 기준으로 훈련된 모델들의 1-crop 에러율은 아래와 같습니다.
데이터셋을 넣으니 원문에 가까우면서도 더 부드럽게 읽히는것같습니다~ 제안 감사합니다 ㅎㅎ

2022-08-20 02:19 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +# 예제 (torch vision 필요)
라이브러리 이름이기 때문에 붙이는게 좋아보입니다~ 반영하였습니다 ㅎㅎ

2022-08-20 02:54 UTC, codingbowoo reviewed
몇가지 코멘트 드립니다. 확인 및 선택적 반영 해주시면 PR 머지하도록 하겠습니다. 
수고하셨습니다! 👍

2022-08-20 02:54 UTC, codingbowoo commented on pytorch_vision_squeezenet.md
> +# pytorch에서 웹사이트에서 이미지 다운로드
이미지 다운로드 -> 예제 이미지 다운로드로 수정해야 할 것 같습니다.

2022-08-20 02:54 UTC, codingbowoo commented on pytorch_vision_squeezenet.md
> +샘플 실행 코드는 아래와 같습니다.
샘플이라는 단어를 살려두기보다는 실행 예제는 아래와 같습니다. 등으로 번역하는 것은 어떨까요?

2022-08-20 02:54 UTC, codingbowoo commented on pytorch_vision_squeezenet.md
> +# 빠르게 실행하기 위해 가능한 경우 model 과 input image 를 gpu 를 사용하여 조정
gpu 를 사용하여 조정 부분을 GPU로 이동/ GPU를 사용하도록 설정 등으로 수정하면 좀더 자연스러울 것 같네요!

2022-08-20 02:54 UTC, codingbowoo commented on pytorch_vision_squeezenet.md
> +# 해당 신뢰 점수는 softmax를 취해 확률 값으로 변환가능합니다.
확률 값/ 확률값 중 한가지로 통일해주시면 좋을 것 같습니다. (아래에도 해당 단어가 나오고, 확률값 으로 띄어쓰기 없이 표기하셨어요)
개인적으로는 확률값 을 추천드립니다. 사전에 등재된 단어는 아니지만, https://ko.dict.naver.com/#/entry/koko/05b7473333e54e18bcea9bf6dfc45929 이런 식의 용례가 있어서요!

2022-08-20 02:54 UTC, codingbowoo commented on pytorch_vision_squeezenet.md
> +`squeezenet1_0` 수준의 정확도를 유지하며 2.4배 계산이 덜 필요하고, `squeezenet1_0`보다 변수(parameters)의 수가 적습니다.
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md 에 따라
parameter는 매개변수로 번역하고, 괄호 안의 글자는 지워도 괜찮을 것 같습니다.

2022-08-20 05:43 UTC, songhee23 commented on pytorch_vision_squeezenet.md
> +# 가능한 경우 model 과 input image 를 gpu 를 사용하도록 조정
좋습니다 😃

2022-08-20 05:44 UTC, songhee23 commented on pytorch_vision_squeezenet.md
> +# 웹사이트에서 이미지 다운로드
감사합니다! 😄

2022-08-23 10:02 UTC, Taeyoung96 reviewed
몇 가지 의견 남겨봤습니다. 감사합니다!

2022-08-23 10:02 UTC, Taeyoung96 commented on pytorch_vision_squeezenet.md
> +# Imagenet 라벨 다운로드
Imagenet이 고유명사이니까 ImageNet으로 대문자를 맞춰주는건 어떨까요?

2022-08-23 10:02 UTC, Taeyoung96 commented on pytorch_vision_squeezenet.md
> +Imagenet 데이터셋 기준으로 훈련된 모델들의 1-crop 에러율은 아래와 같습니다.
위 Imagenet과 동일하게 ImageNet으로 바꾸는게 어떤지 의견드립니다. :smile:

2022-08-27 03:28 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +# pytorch에서 웹사이트에서 이미지 다운로드
예제 이미지 다운로드로 수정하였습니다!

2022-08-27 03:30 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +# Imagenet 1000개 범주에 대한 신뢰 점수를 나타내는 텐서 반환
> 외래어 표기법 그대로 토치비전도 괜찮을거같아요.

토치비전으로 수정하였습니다~ 위 용례에 대해서는 통일된 방법이 있으면 좋겠네요 ㅎㅎ

> 의견이긴 보다는 shape 을 어떤식으로 표현할지 저도 항상 의문이어서 남겨봅니다.

shape 번역이 생각보다 까다로운것같습니다 :)

2022-08-27 03:30 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +샘플 실행 코드는 아래와 같습니다.
실행 예제라고 번역하니 훨씬 깔끔한것 같네요 :)

2022-08-27 03:30 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +# 빠르게 실행하기 위해 가능한 경우 model 과 input image 를 gpu 를 사용하여 조정
`gpu 를 사용하도록 설정`으로 바꿔보았습니다 👍

2022-08-27 03:31 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +# 해당 신뢰 점수는 softmax를 취해 확률 값으로 변환가능합니다.
모두 `확률값`으로 통일하였습니다. 의견감사드립니다!

2022-08-27 03:32 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +`squeezenet1_0` 수준의 정확도를 유지하며 2.4배 계산이 덜 필요하고, `squeezenet1_0`보다 변수(parameters)의 수가 적습니다.
용례집에 있었군요! 매개변수로 반영하였습니다!

2022-08-27 03:32 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +# Imagenet 라벨 다운로드
적절해보입니다 :) ImageNet으로 변경하였습니다~

2022-08-27 03:32 UTC, zhoonit commented on pytorch_vision_squeezenet.md
> +Imagenet 데이터셋 기준으로 훈련된 모델들의 1-crop 에러율은 아래와 같습니다.
반영하였습니다! 의견감사드립니다 :)

2022-08-27 04:55 UTC, codingbowoo approved these changes
LGTM!

2022-08-27 04:56 UTC, merged