SSD 번역
PyTorchKorea/hub-kr pull request #36
Opened 2022-08-10 04:57 UTC by cpprhtn

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #35 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
SSD 모델 번역

2022-08-13 08:33 UTC, yh00214 commented on nvidia_deeplearningexamples_ssd.md
> +SSD300 모델은 "단일 심층 신경망을 사용하여 이미지에서 물체를 감지하는 방법"으로 설명 하는 [SSD: Single Shot MultiBox Detector](https://arxiv.org/abs/1512.02325) 논문을 기반으로 합니다. 입력 크기는 300x300으로 고정되어 있습니다.
'describes SSD as' 가 번역되어 있지 않습니다. 'SSD300 모델은 **SSD를** "단일 심층 신경망을 사용하여...' 로 변경하면 문장의 의미가 명확해질 것 같습니다.

2022-08-13 08:33 UTC, yh00214 commented on nvidia_deeplearningexamples_ssd.md
> +이 모델과 논문에 설명된 모델의 큰 차이점은 백본(backbone)에 있습니다. 논문에서 사용한 VGG 모델은 더 이상 사용되지 않으며 ResNet-50 모델로 대체되었습니다.
'논문에서 사용한' 을 추가해 문장의 의미를 명확하게 만든 점이 정말 좋다고 생각합니다.

2022-08-13 10:23 UTC, cpprhtn commented on nvidia_deeplearningexamples_ssd.md
> +SSD300 모델은 "단일 심층 신경망을 사용하여 이미지에서 물체를 감지하는 방법"으로 설명 하는 [SSD: Single Shot MultiBox Detector](https://arxiv.org/abs/1512.02325) 논문을 기반으로 합니다. 입력 크기는 300x300으로 고정되어 있습니다.
꼼꼼한 피드백 감사합니다!

2022-08-13 10:48 UTC, cpprhtn commented on nvidia_deeplearningexamples_ssd.md
> +SSD300 모델은 "단일 심층 신경망을 사용하여 이미지에서 물체를 감지하는 방법"으로 설명 하는 [SSD: Single Shot MultiBox Detector](https://arxiv.org/abs/1512.02325) 논문을 기반으로 합니다. 입력 크기는 300x300으로 고정되어 있습니다.
추가하려고 다시 읽어봤는데 'SSD300 모델은 "~" **으로 설명하는 SSD** 논문을 기반으로 합니다.'  와 같은 형태로 `describes SSD as`를 번역해둔 상태입니다. 혹시 더 좋은 의견 있으시면 언제나 환영입니다!!

2022-08-17 06:02 UTC, Lee-JaeWon requested changes

2022-08-17 06:02 UTC, Lee-JaeWon commented on nvidia_deeplearningexamples_ssd.md
> +이 모델과 논문에 설명된 모델의 큰 차이점은 백본(backbone)에 있습니다. 논문에서 사용한 VGG 모델은 더 이상 사용되지 않으며 ResNet-50 모델로 대체되었습니다.
`논문에서 사용한' 표현을 추가한 것이 굉장히 매끄러워 좋다고 생각했습니다.

원문에서 `Specifiacally`를 사용하여 강조한 느낌을 주었는데, 번역본에서도 이를 살리면 좋지 않을까 한 번 의견을 남겨봅니다.
> 특히, 논문에서 사용한 VGG 모델은 더 이상 사용되지 않으며 ResNet-50 모델로 대체되었습니다.

2022-08-20 02:29 UTC, zhoonit commented on nvidia_deeplearningexamples_ssd.md
> +SSD300 모델은 "단일 심층 신경망을 사용하여 이미지에서 물체를 감지하는 방법"으로 설명 하는 [SSD: Single Shot MultiBox Detector](https://arxiv.org/abs/1512.02325) 논문을 기반으로 합니다. 입력 크기는 300x300으로 고정되어 있습니다.
문장이 길기 때문에, 원문의 의미를 살려 문장을 두개로 쪼개는 것도 좋을 것 같습니다 ㅎㅎ

```
1. SSD300 Model 은 [SSD: ~] 논문을 기반으로 하고있습니다.
2. 이 논문은 SSD를 "단일 심층 신경망을 사용하여 이미지에서 물체를 감지하는 방법"으로 설명/정의/묘사하고 있습니다.
```

2022-08-20 02:34 UTC, zhoonit commented on nvidia_deeplearningexamples_ssd.md
> +[Speed/accuracy trade-offs for modern convolutional object detectors](https://arxiv.org/abs/1611.10012) 논문에서 , 백본에 대해 다음과 같은 개선이 이루어졌습니다.:
쉼표 앞 띄워쓰기를 지우면 더 좋을것 같습니다.

쌍점(콜론)의 경우도, '다음과 같이' 라고 설명하고 있기 때문에 제거해도 좋을것 같습니다 ㅎㅎ
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=62085

```suggestion
[Speed/accuracy trade-offs for modern convolutional object detectors](https://arxiv.org/abs/1611.10012) 논문에서, 백본에 대해 다음과 같은 개선이 이루어졌습니다.
```

2022-08-20 02:35 UTC, zhoonit commented on nvidia_deeplearningexamples_ssd.md
> +백본 뒤에는 5개의 컨볼루션 레이어가 추가됩니다. 또한 컨볼루션 레이어 외에도 6개의 detection heads를 추가했습니다.
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md
용례집에 따라 컨볼루션의 경우 '합성곱' 으로 번역하는 것은 어떨지 제안드립니다 ㅎㅎ

2022-08-20 02:37 UTC, zhoonit commented on nvidia_deeplearningexamples_ssd.md
> +COCO 데이터셋에 대해 사전에 학습된 SSD 모델과, 모델의 입력 및 출력에 대한 편리하고 포괄적인 형식 지정을 위한 유틸리티를 불러옵니다.
`COCO 데이터셋에 대해 사전에 학습된 ` 이 매끄러운것 같습니다 👍

2022-08-20 02:42 UTC, zhoonit commented on nvidia_deeplearningexamples_ssd.md
> +보다 포괄적인 형식으로 합리적인 탐지(신뢰도>40%)만 얻도록 이 출력을 필터링해 보겠습니다.
문맥으로 미루어보아 `포괄적인 형식으로 합리적인 탐지` 를 아래와 같이 번역하는 것은 어떨까요?

```suggestion
보다 의미있는 결과(신뢰도>40%)만 필터링 해 보겠습니다.
```

2022-08-20 02:48 UTC, zhoonit commented on nvidia_deeplearningexamples_ssd.md
> +기본적으로 입력 이미지당 SSD 네트워크의 가공되기 이전의 출력에서 국소화 및 클래스 확률 분포가 있는 8732개의 상자가 포함됩니다.
국소화라는 개념이 잘 와닿지 않아서, localization 이라는 용어를 그대로 사용하거나, 의미에 맞게 다시쓰는 것은 어떨까요?

```suggestion
ssd network의 기본 출력값은 객체의 위치를 식별하는 8732개의 box 와  클래스 확률 분포를 담고 있습니다.
```

2022-08-20 02:50 UTC, zhoonit commented on nvidia_deeplearningexamples_ssd.md
> +이 모델은 COCO 데이터셋에 대해 학습되었고, 클래스 ID를 객체 이름으로 번역하기 위해 유틸리티에 접근합니다.
class Id 를 (사람이 식별할 수 있는) 객체 이름으로 바꾸기 위해 coco 데이터셋에 접근이 필요합니다. 
정도로 문맥에 맞게 다시 쓰는 것은 어떨까요?

2022-08-20 08:44 UTC, cpprhtn commented on nvidia_deeplearningexamples_ssd.md
> +SSD300 모델은 "단일 심층 신경망을 사용하여 이미지에서 물체를 감지하는 방법"으로 설명 하는 [SSD: Single Shot MultiBox Detector](https://arxiv.org/abs/1512.02325) 논문을 기반으로 합니다. 입력 크기는 300x300으로 고정되어 있습니다.
확인했습니다! 감사합니다

2022-08-20 08:45 UTC, cpprhtn commented on nvidia_deeplearningexamples_ssd.md
> +[Speed/accuracy trade-offs for modern convolutional object detectors](https://arxiv.org/abs/1611.10012) 논문에서 , 백본에 대해 다음과 같은 개선이 이루어졌습니다.:
감사합니다! 반영하겠습니다.
쉼표 앞 띄워쓰기는 의도한건 아니고 오타였는데 발견해주셨네요 :)

2022-08-20 08:45 UTC, cpprhtn commented on nvidia_deeplearningexamples_ssd.md
> +백본 뒤에는 5개의 컨볼루션 레이어가 추가됩니다. 또한 컨볼루션 레이어 외에도 6개의 detection heads를 추가했습니다.
감사합니다

2022-08-20 08:47 UTC, cpprhtn commented on nvidia_deeplearningexamples_ssd.md
> +보다 포괄적인 형식으로 합리적인 탐지(신뢰도>40%)만 얻도록 이 출력을 필터링해 보겠습니다.
좀더 한글 스러운 번역이 되겠군요! 훨씬 이해하기 편해졌네요 감사합니다.

2022-08-20 08:48 UTC, cpprhtn commented on nvidia_deeplearningexamples_ssd.md
> +이 모델은 COCO 데이터셋에 대해 학습되었고, 클래스 ID를 객체 이름으로 번역하기 위해 유틸리티에 접근합니다.
어색한부분 너무 잘 찾아주시네요.. 최고입니다

2022-08-20 08:49 UTC, cpprhtn commented on nvidia_deeplearningexamples_ssd.md
> +기본적으로 입력 이미지당 SSD 네트워크의 가공되기 이전의 출력에서 국소화 및 클래스 확률 분포가 있는 8732개의 상자가 포함됩니다.
예시까지 적어주시다니 감사합니다. 리뷰해준거 한번에 반영해서 PR할려구합니다!

2022-08-27 03:34 UTC, zhoonit approved these changes
깔끔해보입니다. 의견 반영해주셔서 감사합니다 :)

2022-08-27 05:02 UTC, codingbowoo commented on nvidia_deeplearningexamples_ssd.md
> +[Speed/accuracy trade-offs for modern convolutional object detectors](https://arxiv.org/abs/1611.10012) 논문에서 , 백본에 대해 다음과 같은 개선이 이루어졌습니다.:
띄워쓰기 -> 띄어쓰기로 정정해드리고 사라지겠습니다 🌟

2022-08-27 07:03 UTC, Taeyoung96 reviewed
LGTM 👍   
@zhoonit 님의 피드백 덕분에 매끄럽게 번역이 진행된 것 같습니다!

2022-09-03 06:13 UTC, Taeyoung96 approved these changes

2022-09-03 06:14 UTC, merged