Translate ghostnet
PyTorchKorea/hub-kr pull request #40
Opened 2022-08-14 05:02 UTC by KyubumShin

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #39

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
Ghostnet 번역 추가

2022-08-14 08:55 UTC, Lee-JaeWon requested changes
전체적으로 잘 번역되어있어, 이외의 사소한 부분에 대해 리뷰를 해보았습니다:)

2022-08-14 08:55 UTC, Lee-JaeWon commented on pytorch_vision_ghostnet.md
> +# 예시 코드 (torchvision 필요)
`excution`의 의미를 살려도 좋지 않을까 의견을 남겨봅니다.

`실행 예시 코드` 혹은 `예시 실행 코드`와 같이 코드가 실행을 위한 것임을 밝혀도 좋을 것 같습니다.

2022-08-14 08:55 UTC, Lee-JaeWon commented on pytorch_vision_ghostnet.md
> +# 이미지넷 1000개의 클래스의 신뢰점수를 포함하는 (1000,) 의 텐서
ImageNet Dataset은 데이터셋의 이름이니까 `이미지넷(ImageNet)`과 같이 본래의 이름을 명시해주면 어떠할지 한번 의견을 남겨봅니다. (혹시나 `이미지넷`이라는 단어를 처음본다면 네트워크 이름으로 혼동할 수도 있을거란 생각이 들어 영문 이름도 남겨주면 좋을 것 같아 적어봤습니다)

2022-08-14 08:55 UTC, Lee-JaeWon commented on pytorch_vision_ghostnet.md
> +# 이미지 당 top 카테고리를 보여줌
@zhoonit 님의 PR #32 vision_squeezenet 모델 번역에서 이 부분에 대해 `확률값이 가장 높은 범주 출력`라고 번역을 해주셨는데 이러한 느낌의 의역도 좋지 않을까하여 마찬가지로 의견을 남겨봅니다!

2022-08-20 03:03 UTC, zhoonit commented on docs/model_contribute_guide.md
> +# Model Contributing Guide line
pr (Ghostnet 번역)와 달라보여 의도를 가지고 포함되었는지 궁금합니다.

2022-08-20 03:09 UTC, zhoonit commented on pytorch_vision_ghostnet.md
> +고스트넷 아키텍처는 다양한 특징 맵을 효율적인 연산으로 생성하는 고스트 모듈 구조로 이루어집니다. 고유한 특징 맵을 기반으로 한 효율적인 연산으로 추론에 기반이 되는 고유 특징들을 충분하게 드러내는 고스트 특징 맵을 생성합니다. 벤치마크에서 수행된 실험을 통해 속도와 정확도의 상충 관계에 관한 고스트넷의 우수성을 보여줍니다.
`based on intrinsic feature maps` 를 살려,

```diff
- 고유한 특징 맵을 기반으로 한 효율적인 연산으로 추론에 기반이 되는 고유 특징들을 충분하게 드러내는 고스트 특징 맵을 생성합니다. 
+ 고스트넷은 내부적으로 특징맵을 가지고 있습니다.
+ 이 특징맵의 정보를 온전히 드러내기 위해 간단한 연산을 거쳐 고스트 특징맵을 다량으로 만들어냅니다.
```
처럼 번역하는 것은 어떨지 제안드립니다 :)

2022-08-20 07:37 UTC, KyubumShin commented on docs/model_contribute_guide.md
> +# Model Contributing Guide line
앗 이 부분은 branch 분리해서 따로 작업하던 부분인데 섞여 들어가 있네요! 수정하겠습니다

2022-08-20 07:39 UTC, JDhyeok requested changes

2022-08-20 07:39 UTC, JDhyeok commented on pytorch_vision_ghostnet.md
> +# output은 정규화되지 않은 스코어로 얻어짐. 확률을 얻기 위해 소프트맥스를 사용할 수 있음
완전한 문장에서 끝을 `'-ㅁ/음'체`과 `'-다'체` 두 가지가 혼용되고 있는데, 한 가지 어체로 통일해주시면 더 좋은 번역이 될 것 같습니다. :)

2022-08-20 07:42 UTC, KyubumShin commented on pytorch_vision_ghostnet.md
> +# output은 정규화되지 않은 스코어로 얻어짐. 확률을 얻기 위해 소프트맥스를 사용할 수 있음
이 부분 같은 경우에는 의도적으로 주석은 "-ㅁ"로 본문은 "-다" 로 번역하였는데 하나로 통일 하는 것이 더 좋을까요?

2022-08-27 07:34 UTC, Taeyoung96 reviewed
매끄러운 번역 감사드립니다!  
다른 분들의 comment를 반영하여 업데이트 해주시면 감사드리겠습니다. 😃

2022-08-27 07:34 UTC, Taeyoung96 commented on pytorch_vision_ghostnet.md
> +# output은 정규화되지 않은 스코어로 얻어짐. 확률을 얻기 위해 소프트맥스를 사용할 수 있음
제 의견을 드리자면 하나로 통일하는 것이 좋을 것 같습니다. 😄

2022-08-28 10:16 UTC, KyubumShin commented
브랜치 오염으로 인해서 위의 리뷰 반영해서 새로 PR 날렸습니다!

2022-08-28 10:16 UTC, closed without merging