pytorch_vision_resnext 번역
PyTorchKorea/hub-kr pull request #55
Opened 2022-08-23 06:50 UTC by FollowerOfScriabin

pytorch_vision_resnext.md 파일의 번역본입니다.

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #41

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

2022-08-27 06:27 UTC, yh00214 requested changes
수고하셨습니다! 훌륭한 번역이었습니다.
중간에 한 군데만 코멘트를 달았으니 참고해주시기 바랍니다.

2022-08-27 06:27 UTC, yh00214 commented on pytorch_vision_resnext.md
> +# output은 shape가 [1000]인 Tensor 자료형이며, 이는 Imagenet 데이터셋의 각 클래스에 대한 모델의 확신도(confidence)를 나타냄.
1. Imagenet에 대한 지식이 부족한 분들이 본다고 생각한다면, 원문을 살려 'Imagenet 데이터셋의 1000개의 각 클래스들에 대한 확신도' 같이 1000개의 클래스를 명시해 주는 것이 좋을 것 같습니다.
2. 다른 번역 문장의 어미와 비교했을 때, 통일성을 위해 '나타냅니다.'로 바꾸는 것을 제안합니다.

2022-08-28 12:08 UTC, FollowerOfScriabin commented on pytorch_vision_resnext.md
> +# output은 shape가 [1000]인 Tensor 자료형이며, 이는 Imagenet 데이터셋의 각 클래스에 대한 모델의 확신도(confidence)를 나타냄.
리뷰사항 반영하였습니다. 감사합니다.

2022-09-03 03:05 UTC, zhoonit commented on pytorch_vision_resnext.md
> +이중 두가지 버전의 모델 성능은 아래와 같습니다. 각 모델의 레이어 개수는 각 50, 101개입니다.
Here we have the 2 versions of resnet models, 의 의미를 살려 아래와 같이 번역하면 어떨지 제안드립니다 :)

```suggestion
여기서는 50개의 레이어와 101개의 레이어를 가지는 2개의 resnet 모델을 제공하고 있습니다.
각 모델 성능은 아래와 같습니다.
```

2022-09-03 04:06 UTC, FollowerOfScriabin commented on pytorch_vision_resnext.md
> +이중 두가지 버전의 모델 성능은 아래와 같습니다. 각 모델의 레이어 개수는 각 50, 101개입니다.
리뷰 사항 반영하였습니다. 감사합니다.

2022-09-03 07:24 UTC, Taeyoung96 reviewed
@FollowerOfScriabin   
몇 가지 comment를 남겨봤습니다.  
확인해주시고 update해주시면 감사드리겠습니다.

2022-09-03 07:24 UTC, Taeyoung96 commented on pytorch_vision_resnext.md
> +모든 사전 훈련된 모델들은 입력 이미지가 동일한 방식으로 정규화되었다고 상정합니다.
`상정합니다`는 오타일까요?  
`가정합니다`라고 바꾸는 것이 조금 더 적절해 보입니다.

2022-09-03 07:24 UTC, Taeyoung96 commented on pytorch_vision_resnext.md
> +각 이미지는 `[0, 1]`의 범위 내에서 로드되어야 하며, `mean = [0.485, 0.456, 0.406]` 과 `std = [0.229, 0.224, 0.225]`을 이용해 정규화되어야 합니다.
`로드되어야`라는 단어도 `불러와야`로 번역하는 것이 어떤지 제안드립니다.

2022-09-03 07:24 UTC, Taeyoung96 commented on pytorch_vision_resnext.md
> +input_batch = input_tensor.unsqueeze(0) # 모델에서 가정하는대로 미니배치 생성
`모델에서 가정하는 대로 미니 배치 생성`으로 띄어쓰기를 바꿔야 적절해 보입니다.

2022-09-03 07:24 UTC, Taeyoung96 commented on pytorch_vision_resnext.md
> +# output은 정규화되지 않았으므로, 확률화하기 위해 softmax 함수를 처리합니다.
전체적으로 주석을 마무리할 때, 통일성을 가지면 좋을 것 같습니다.  
어떤 주석은 단어로 끝나고, 어떤 주석은 `~이다`로 끝나는 것 같네요. 😄

2022-09-03 07:24 UTC, Taeyoung96 commented on pytorch_vision_resnext.md
> +# 파이토치 웹 사이트에서 다운로드한 이미지 입니다.
맞춤법 상 `이미지입니다.`로 붙여야 할 것 같습니다.

2022-09-03 07:24 UTC, Taeyoung96 commented on pytorch_vision_resnext.md
> +여기서는 50개의 레이어와 101개의 레이어를 가지는 2개의 resnet 모델을 제공하고 있습니다.
[용어 사용 규칙](https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md#%EC%9A%A9%EC%96%B4-%EC%82%AC%EC%9A%A9-%EA%B7%9C%EC%B9%99)을 참고하면 레이어는 계층으로 번역이 되는 것이 적절해 보입니다.

2022-09-03 07:24 UTC, Taeyoung96 commented on pytorch_vision_resnext.md
> +# output은 shape가 [1000]인 Tensor 자료형이며, 이는 Imagenet 데이터셋의 1000개의 각 클래스에 대한 모델의 확신도(confidence)를 나타냅니다.
Imagenet은 아래와 통일성을 갖기 위해 `ImageNet`으로 수정하는 것이 어떨까요?

2022-09-03 07:25 UTC, codingbowoo commented on pytorch_vision_resnext.md
> +# 파이토치 웹 사이트에서 다운로드한 이미지 입니다.
```suggestion
# 파이토치 웹 사이트에서 이미지 다운로드 
```
아래에서 create a mini-batch as expected by the model을 모델에서 가정하는대로 미니배치 생성 이라고 번역해주신 것처럼, 
이 부분도 주석을 보는 분들께 이부분은 다운로드 하는 부분이다~ 하는 내용이 전해져야 할 것 같습니다.

2022-09-03 07:25 UTC, codingbowoo commented on pytorch_vision_resnext.md
> +input_batch = input_tensor.unsqueeze(0) # 모델에서 가정하는대로 미니배치 생성
```suggestion
input_batch = input_tensor.unsqueeze(0) # 모델에서 가정하는 대로 미니배치 생성
```
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=114792 에 따라 의존명사의 쓰임으로 보여, 띄어쓰기를 넣어주세요!

2022-09-03 07:26 UTC, codingbowoo commented on pytorch_vision_resnext.md
> +input_batch = input_tensor.unsqueeze(0) # 모델에서 가정하는대로 미니배치 생성
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=114792 에 따라 의존명사의 쓰임으로 보이네요.

2022-09-03 10:19 UTC, mindongjun commented on pytorch_vision_resnext.md
> +모든 사전 훈련된 모델들은 입력 이미지가 동일한 방식으로 정규화되었다고 상정합니다.
안녕하세요 
해당 내용은 `가정`과 `상정`의 의미 차이에 따라
`상정합니다`가 더 적절한 뜻이 아닐까 생각됩니다.

> ‘상정’은 ‘딱 잘라서 판단하고 결정함’이라는 ‘단정’의 뜻이, ‘가정’은 ‘(임시로) 그렇다고 여김’이라는 ‘인정’의 뜻이 들어 있으므로, 이러한 뜻 차이를 고려하셔서 문맥에 맞게 ‘상정’이나 ‘가정’을 쓰시면 되겠습니다.
>
> 상정(想定)
>
> 「명사」
>
> 어떤 정황을 가정적으로 생각하여 단정함. 또는 그런 단정.
>
> ¶ 이 우스꽝스러운 상정을 남들이 일소에 부칠지라도 그때의 나로서는 꽤나 심각한 상정이었다.≪윤후명, 별보다 멀리≫
>
> 가정(假定)
>
> 「명사」
>
> 「1」사실이 아니거나 또는 사실인지 아닌지 분명하지 않은 것을 임시로 인정함.
>
> ¶ 그의 의식 속에는 만약이라는 가정이 항상 존재하고 있다./6월 초 선거가 실시된다는 가정 아래 준비를 해 왔다.

관련 국립국어원 내용 링크로 남겨드립니다.

https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=96465

2022-09-09 06:34 UTC, Taeyoung96 commented
@FollowerOfScriabin   
comment에 대해서 update 및 의견을 말씀해주시면 감사드리겠습니다.

2022-09-15 10:04 UTC, Taeyoung96 approved these changes
리뷰 사항 반영해주셔서 감사드립니다.

2023-04-02 03:54 UTC, hyoyoung approved these changes
good

2023-04-02 03:55 UTC, merged