SlowFast 번역
PyTorchKorea/hub-kr pull request #57
Opened 2022-08-25 11:46 UTC by cpprhtn

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #45 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
SlowFast 모델에 대한 번역을 진행하였습니다.

2022-09-03 03:09 UTC, zhoonit commented on facebookresearch_pytorchvideo_slowfast.md
> +토치 허브 모델이 훈련된 Kinetics 400 데이터셋에 대해 레이블 매핑이 된 ID를 다운로드합니다. 이는 예측된 클래스 ID에서 카테고리 레이블 이름을 가져오는데 사용됩니다.
목적어가 'the id to label mapping' 이기 때문에
'레이블 매핑이 된 ID 다운로드' -> 'id에서의 label 매핑'을 다운로드  정도로 번역하는 것은 어떨까요??

2022-09-03 03:13 UTC, cpprhtn commented on facebookresearch_pytorchvideo_slowfast.md
> +토치 허브 모델이 훈련된 Kinetics 400 데이터셋에 대해 레이블 매핑이 된 ID를 다운로드합니다. 이는 예측된 클래스 ID에서 카테고리 레이블 이름을 가져오는데 사용됩니다.
헉.. 감사합니다. [3D ResNet](https://github.com/PyTorchKorea/hub-kr/pull/63)에도 동일한 형태로 번역해두었는데 둘다 반영하겠습니다!

2022-09-03 03:15 UTC, cpprhtn commented on facebookresearch_pytorchvideo_slowfast.md
> +토치 허브 모델이 훈련된 Kinetics 400 데이터셋에 대해 레이블 매핑이 된 ID를 다운로드합니다. 이는 예측된 클래스 ID에서 카테고리 레이블 이름을 가져오는데 사용됩니다.
`ID에서의 레이블 매핑 정보를 다운로드합니다` 의 문장으로 수정했습니다!

2022-09-14 09:19 UTC, cpprhtn commented on facebookresearch_pytorchvideo_slowfast.md
> +# 비디오 입력을 정규화하기 위해 transform 함수를 적용합니다.
헛 감사합니다. 반영하겠습니다 :)

2022-09-14 12:16 UTC, Taeyoung96 reviewed
@cpprhtn 
번역 하시느라 고생하셨습니다. :smile:

2022-09-14 12:40 UTC, cpprhtn commented on facebookresearch_pytorchvideo_slowfast.md
>  Download the id to label mapping for the Kinetics 400 dataset on which the torch hub models were trained. This will be used to get the category label names from the predicted class ids.
제가 영어 원문보면서 번역한뒤에 지우는데,, 저문장 지우는걸 까먹은거 같습니다!!
지우도록 하겠습니다 :)

2022-09-14 12:40 UTC, cpprhtn commented on facebookresearch_pytorchvideo_slowfast.md
> +# 시작 및 종료 기간을 지정하여 불러올 클립의 기간을 선택합니다.
감사합니다 👍

2022-09-14 12:40 UTC, cpprhtn commented on facebookresearch_pytorchvideo_slowfast.md
> +# 모델을 통해 입력클립을 전달합니다.
좋은의견 감사합니다

2022-09-14 14:48 UTC, codingbowoo requested changes
일부 의미상 번역 수정 및 논의가 필요할 것 같습니다.

2022-09-14 14:48 UTC, codingbowoo commented on facebookresearch_pytorchvideo_slowfast.md
>  #### Imports
해당 항목도 번역 부탁드립니다. 아래 번역하신 내용 상 "불러오기" 정도면 괜찮을 것 같다고 생각합니다 :)

2022-09-14 14:48 UTC, codingbowoo commented on facebookresearch_pytorchvideo_slowfast.md
> +토치 허브 모델이 훈련된 Kinetics 400 데이터셋에 대해 ID에서의 레이블 매핑 정보를 다운로드합니다. 이는 예측된 클래스 ID에서 카테고리 레이블 이름을 가져오는데 사용됩니다.
```suggestion
토치 허브 모델이 훈련된 Kinetics 400 데이터셋을 위한 id-레이블 매핑 정보를 다운로드합니다. 이는 예측된 클래스 id에 카테고리 레이블 이름을 붙이는 데 사용됩니다.
```
의미상 일부 번역을 수정할 것을 제안드립니다. 
두번째 문장에는 의역을 과하게(?) 넣어 봤는데요, 입맛에 맞게 수정해주시면 좋을 것 같습니다 :)

2022-09-14 14:48 UTC, codingbowoo commented on facebookresearch_pytorchvideo_slowfast.md
> +# 레이블 이름 매핑에 대한 ID 만들기
```suggestion
# id-레이블 이름 매핑 만들기
```
위와 동일하게 의미상 일부 번역 수정을 제안드립니다.

2022-09-14 14:48 UTC, codingbowoo commented on facebookresearch_pytorchvideo_slowfast.md
> +#### 입력 형태에 대한 정의
```suggestion
#### 입력 변환에 대한 정의
```
내용상 입력한 비디오 프레임을 텐서로 변환하는 '변환'에 대한 정의로 보여, 수정 제안 드립니다.
다만, `입력 변환` 이라는 표현이 좀 어색한 것 같기도 하네요...

2022-09-14 14:48 UTC, codingbowoo commented on facebookresearch_pytorchvideo_slowfast.md
> +# 시작 및 종료 구간을 지정하여 불러올 클립의 길이 선택합니다.
```suggestion
# 시작 및 종료 구간을 지정하여 불러올 클립의 길이를 선택합니다.
```

2022-09-14 14:48 UTC, codingbowoo commented on facebookresearch_pytorchvideo_slowfast.md
> +# start_sec는 영상에서 행동이 시작되는 위치와 일치해야합니다.
```suggestion
# start_sec는 영상에서 행동이 시작되는 위치와 일치해야 합니다.
```

2022-09-14 14:48 UTC, codingbowoo commented on facebookresearch_pytorchvideo_slowfast.md
> +# 영상 입력을 정규화하기 위해 변형(transform) 함수를 적용합니다.
주석에서 의미하는 바는 transform 메소드를 칭하기보다는 변환을 적용한다는 일반적인 뜻인 것으로 보입니다. 
그러나 헷갈릴 수 있으니 @cpprhtn 님께서 처음 적어주신 것처럼 transform 함수라고 명시해 봤는데 어떠실까요?
```suggestion
# 영상 입력을 정규화하기 위한 변환(transform 함수)을 적용합니다.
```

2022-09-14 14:54 UTC, cpprhtn commented on facebookresearch_pytorchvideo_slowfast.md
> +# 영상 입력을 정규화하기 위해 변형(transform) 함수를 적용합니다.
좋은것 같습니다 :) LGTM 👍

2022-09-14 14:56 UTC, cpprhtn commented on facebookresearch_pytorchvideo_slowfast.md
>  #### Imports
감사합니다!

2023-04-02 03:56 UTC, hyoyoung approved these changes
good

2023-04-02 07:22 UTC, codingbowoo approved these changes

2023-04-02 14:53 UTC, merged