ProxylessNAS 번역
PyTorchKorea/hub-kr pull request #60
Opened 2022-08-27 04:46 UTC by cpprhtn

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #59 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

ProxylessNAS 문서 번역

2022-08-27 08:12 UTC, yh00214 requested changes
번역 수고하셨습니다! 전체적으로 훌륭합니다~

2022-08-27 08:12 UTC, yh00214 commented on pytorch_vision_proxylessnas.md
> +i.e. `H`와 `W`가 최소 `224`의 크기를 가지는 `(3 x H x W)`형태의 3채널 RGB 이미지의 미니배치
다른 대부분의 번역에서 `i.e`를 `즉,` 으로 번역하고, 자연스러운 문장 구조를 띄도록 변경하였습니다. 원문 문장 구조를 유지하기 위해 이렇게 번역하신 것 같은데, 다른 번역과 통일성을 생각하면 자연스러운 문장 구조로 번역하시는 것도 좋을 것 같습니다.

2022-08-27 08:33 UTC, cpprhtn commented on pytorch_vision_proxylessnas.md
> +i.e. `H`와 `W`가 최소 `224`의 크기를 가지는 `(3 x H x W)`형태의 3채널 RGB 이미지의 미니배치
감사합니다! 수정해보겠습니다 :)

2022-09-14 09:33 UTC, KyubumShin commented
전체적으로 잘 번역된 것 같습니다!

2022-09-14 14:12 UTC, Woodywarhol9 reviewed
고생하셨습니다! 
몇 가지 수정 제안드려요

2022-09-14 14:12 UTC, Woodywarhol9 commented on pytorch_vision_proxylessnas.md
> +일반적으로, 사람들은 *모든 하드웨어 플랫폼*에 대해 *하나의 효율적인 모델*을 설계하는 경향이 있습니다. 하지만 하드웨어마다 특성이 다릅니다. 에를 들어 CPU는 더 높은 주파수를 가지지만 GPU는 병렬화에 더 뛰어납니다. 따라서 일반화하는 대신 다양한 하드웨어 플랫폼에 대한 CNN 아키텍처를 **전문화**해야 합니다. 아래에서 볼 수 있듯이, 전문화는
`모든 하드웨어 플랫폼(CPU, GPU, Mobile)`처럼 하드웨어 플랫폼이 뭔지 명시해주면 더 좋을 거 같아요!

`일반화하는 대신 하드웨어 플랫폼에 맞게 CNN 아키텍처를 **전문화**해야 합니다.`
문장을 이런 식으로 바꾸면 더 읽기 좋을 거 같아요!

`전문화는 세 가지 플랫폼 모두에서 상당한 성능 향상을 제공합니다.` 이렇게 해석하면 어떨까요?
`무료`라는 표현은 아마 논문에서 나오는 `search cost` 같은 것이 적다는  의미 같은데 별도의 표나 자료가 없이 갑자기 `무료`라는 표현이 나오면 이해하기 힘들다고 생각해서 제외했습니다.

2022-09-14 14:21 UTC, cpprhtn commented on pytorch_vision_proxylessnas.md
> +일반적으로, 사람들은 *모든 하드웨어 플랫폼*에 대해 *하나의 효율적인 모델*을 설계하는 경향이 있습니다. 하지만 하드웨어마다 특성이 다릅니다. 에를 들어 CPU는 더 높은 주파수를 가지지만 GPU는 병렬화에 더 뛰어납니다. 따라서 일반화하는 대신 다양한 하드웨어 플랫폼에 대한 CNN 아키텍처를 **전문화**해야 합니다. 아래에서 볼 수 있듯이, 전문화는
모든 하드웨어 플랫폼에 대해서는 뒤에 문장에서 예시를 통해 언급해서 안적어도 괜찮을것 같습니다.

나머지 두가지 의견은 너무 좋은 문장인것 같습니다! 👍

2022-09-14 14:29 UTC, codingbowoo requested changes
같이 고민해볼 지점들이 있는 것 같습니다 :)

2022-09-14 14:29 UTC, codingbowoo commented on pytorch_vision_proxylessnas.md
> +# Imagnet의 1000개 클래스에 대한 신뢰도 점수를 가진 1000 형태의 텐서 출력
```suggestion
# Imagenet의 1000개 클래스에 대한 신뢰도 점수를 가진 1000 형태의 텐서 출력
```
오탈자가 있고, shape 1000을 좀 더 자연스럽게 번역할 수 있는 방법이 있을까 고민해보겠습니다.

2022-09-14 14:29 UTC, codingbowoo commented on pytorch_vision_proxylessnas.md
> +일반적으로, 사람들은 *모든 하드웨어 플랫폼*에 대해 *하나의 효율적인 모델*을 설계하는 경향이 있습니다. 하지만 하드웨어마다 특성이 다릅니다. 에를 들어 CPU는 더 높은 주파수를 가지지만 GPU는 병렬화에 더 뛰어납니다. 따라서 일반화하는 대신 하드웨어 플랫폼에 맞게 CNN 아키텍처를 **전문화**해야 합니다. 아래에서 볼 수 있듯이, 전문화는 세 가
```suggestion
일반적으로, 사람들은 *모든 하드웨어 플랫폼*에 대해 *하나의 효율적인 모델*을 설계하는 경향이 있습니다. 하지만 하드웨어마다 특성이 다릅니다. 예를 들어 CPU는 더 높은 주파수를 가지지만 GPU는 병렬화에 더 뛰어납니다. 따라서 모델을 일반화하기보다는 하드웨어 플랫폼에 맞게 CNN 아키텍처를 **전문화**해야 합니다. 아래에서 볼 수 있듯이, 전문화는 세 가지 플랫폼 모두에서 상당한 성능 향상을 제공합니다.
```
1. 오탈자가 있습니다. 
2. CPU가 더 높은 주파수를 가져서 어떤 점이 뛰어난지를 추가 설명해보는건 어떨까 하는 생각이 드네요.
3. specialize를 전문화 로 번역한게 좋네요!
4. 일부 읽기 좋게 문장을 변경해봤는데 어떠실까요?

2022-09-14 14:45 UTC, cpprhtn commented on pytorch_vision_proxylessnas.md
> +# Imagnet의 1000개 클래스에 대한 신뢰도 점수를 가진 1000 형태의 텐서 출력
텐서도 Tensor로 적기로 해서 그것도 고쳐야하네요 하하

2022-09-14 14:47 UTC, cpprhtn commented on pytorch_vision_proxylessnas.md
> +일반적으로, 사람들은 *모든 하드웨어 플랫폼*에 대해 *하나의 효율적인 모델*을 설계하는 경향이 있습니다. 하지만 하드웨어마다 특성이 다릅니다. 에를 들어 CPU는 더 높은 주파수를 가지지만 GPU는 병렬화에 더 뛰어납니다. 따라서 일반화하는 대신 하드웨어 플랫폼에 맞게 CNN 아키텍처를 **전문화**해야 합니다. 아래에서 볼 수 있듯이, 전문화는 세 가
오탈자 넘 잘 찾으십니다!!
2번에대해서는 고민해봐야겠습니다
4번에 대한 의견은 너무 좋은것 같습니다 👍

2023-04-02 07:37 UTC, codingbowoo approved these changes

2023-04-02 14:53 UTC, merged