번역: AlexNet 번역
PyTorchKorea/hub-kr pull request #65
Opened 2022-08-28 06:13 UTC by JDhyeok

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #46 
 
## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
AlexNet 영한 번역

2022-08-28 07:17 UTC, cepiloth reviewed
번역하느라고 수고 하셨습니다.

2022-08-28 07:17 UTC, cepiloth commented on pytorch_vision_alexnet.md
> +input_batch = input_tensor.unsqueeze(0) # 모델에서 요구하는 형식인 mini batch 생성
수고하셨습니다. 미니 배치는 음차표기 그대로 하는것을 추천드려요.
https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md

2022-08-29 10:27 UTC, HyunKyungHan reviewed
번역 수고하셨습니다!!

2022-08-29 10:27 UTC, HyunKyungHan commented on pytorch_vision_alexnet.md
> +모든 사전 훈련된 모델들은 같은 방법으로 정규화된 입력 이미지를 입력받습니다. 예시로, `(3 x H x W)`의 3-채널 RGB 이미지들의 미니 배치일 때 `H`와 `W`의 크기는 224 이상이어야 합니다.
음..이건 그냥 제 생각인데 이 문단의 1-2번째 줄이 재훈님 FCN 번역 1-2번째 줄이랑 거의 비슷해서 번역 내용을 통일해도 좋을 것 같아요! 
다음 팀 회의 때 이야기해봐도 좋을 것 같네요 :)

2022-09-03 07:43 UTC, codingbowoo commented
@JDhyeok 님, 팀원분들 코멘트 반영해주시면 리뷰 및 머지 진행하겠습니다.

2022-09-03 08:26 UTC, cepiloth commented on pytorch_vision_alexnet.md
> +모든 사전 훈련된 모델들은 같은 방법으로 정규화된 입력 이미지를 입력받습니다. 예시로, `(3 x H x W)`의 3-채널 RGB 이미지들의 미니 배치일 때 `H`와 `W`의 크기는 224 이상이어야 합니다.
그러네요 완전히 같아요. 통합해도 될거같아요 :)

2022-09-04 13:06 UTC, JDhyeok commented on pytorch_vision_alexnet.md
> +input_batch = input_tensor.unsqueeze(0) # 모델에서 요구하는 형식인 mini batch 생성
리뷰 감사합니다. 반영 완료했습니다.

2022-09-04 13:06 UTC, JDhyeok commented on pytorch_vision_alexnet.md
> +모든 사전 훈련된 모델들은 같은 방법으로 정규화된 입력 이미지를 입력받습니다. 예시로, `(3 x H x W)`의 3-채널 RGB 이미지들의 미니 배치일 때 `H`와 `W`의 크기는 224 이상이어야 합니다.
리뷰 감사합니다. 반영 완료했습니다.

2022-09-09 06:45 UTC, Taeyoung96 approved these changes
깔끔한 번역 감사드립니다.

2022-09-12 09:20 UTC, codingbowoo requested changes
타이포만 수정해주시면 바로 머지 진행하겠습니다!
깔끔한 번역 감사드립니다. :+1:

2022-09-12 09:20 UTC, codingbowoo commented on pytorch_vision_alexnet.md
> +AlexNet은 2012년도 ImageNet Large Scale Visual Recognition Challnege (ILSVRC)에 참여한 모델입니다. 이 네트워크는 15.3%의 top-5 에러율을 달성했고, 이는 2위보다 10.8%P 낮은 수치입니다. 원 논문의 주요 결론은 높은 성능을 위해 모델의 깊이가 필수적이라는 것이었습니다. 이는 계산 비용이
```suggestion
AlexNet은 2012년도 ImageNet Large Scale Visual Recognition Challenge (ILSVRC)에 참여한 모델입니다. 이 네트워크는 15.3%의 top-5 에러율을 달성했고, 이는 2위보다 10.8%P 낮은 수치입니다. 원 논문의 주요 결론은 높은 성능을 위해 모델의 깊이가 필수적이라는 것이었습니다. 이는 계산 비용이 많이 들지만, 학습 과정에서 GPU의 사용으로 가능해졌습니다.
```
오탈자 수정 부탁드립니다! 
그와 별개로, ILSVRC 라고 명시해주신 점이 좋네요. 👍

2022-09-12 12:45 UTC, JDhyeok commented on pytorch_vision_alexnet.md
> +AlexNet은 2012년도 ImageNet Large Scale Visual Recognition Challnege (ILSVRC)에 참여한 모델입니다. 이 네트워크는 15.3%의 top-5 에러율을 달성했고, 이는 2위보다 10.8%P 낮은 수치입니다. 원 논문의 주요 결론은 높은 성능을 위해 모델의 깊이가 필수적이라는 것이었습니다. 이는 계산 비용이
한국어 맞춤법만 확인하고 영어를 깜빡했네요!
수정했습니다. :)

2022-09-13 12:46 UTC, codingbowoo approved these changes
LGTM! 수고 많으셨습니다!

2022-09-13 12:47 UTC, merged