TROMSFORMER(NMT) 번역
PyTorchKorea/hub-kr pull request #81
Opened 2022-09-03 14:13 UTC by spongebob03

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #68 
## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
TROMSFORMER(NMT)문서 번역

2022-09-04 04:21 UTC, zerojin91 reviewed
몇가지 리뷰 남겨봅니다~!
고생 많으셨습니다 :)

2022-09-04 04:21 UTC, zerojin91 commented on pytorch_fairseq_translation.md
> +영어를 독일어로 번역하기 위해 이 수상 모델 중 하나를 사용합니다:
앞서 소개되었던 대회 수상 모델 중 하나를 사용하여 영어를 독일어로 번역해보겠습니다.
로 바꾸면 어떨까요? (밑에 내용과 매끄럽게 이어지기 위해서)

2022-09-04 04:21 UTC, zerojin91 commented on pytorch_fairseq_translation.md
> +# GPU 사용 (선택적):
선택적 보다는 선택사항으로 표현하는건 어떨까요

2022-09-04 04:21 UTC, zerojin91 commented on pytorch_fairseq_translation.md
> +이러한 테크닉으로 학습된 모델들의 앙상블은 [WMT'19 English-German news
테크닉 보다는 기술 혹은 노하우 등의 표현은 어떨까요

2022-09-04 13:51 UTC, euroversedev reviewed
선희님 안녕하세요 😆 좋은 번역이에요!

2022-09-04 13:51 UTC, euroversedev commented on pytorch_fairseq_translation.md
> +# 수동으로 토큰화:
Manually에 대한 직역을 없애면 이해에 도움이 될 것 같습니다😄

2022-09-05 11:37 UTC, Woodywarhol9 commented
번역 잘해주셨네요! 고생하셨습니다~

2022-09-05 18:25 UTC, mindongjun reviewed
긴 번역인데 아주 편하게 읽히는 것 같습니다. 고생하셨습니다!

2022-09-05 18:25 UTC, mindongjun commented on pytorch_fairseq_translation.md
> +# 수동으로 2진화:
binarize를 번역시에 2진화 보다는 이진화로 하는 것이 더 자연스럽지 않을까 생각됩니다.

2022-09-05 18:25 UTC, mindongjun commented on pytorch_fairseq_translation.md
> +# 예시중 하나를 문자열로 변환하고 탈토큰화
de- 의 의미가 tokenize된것을 다시 복원시키는 의미로 보이니 탈토큰화보다는 비토큰화, 또는 역토큰화로 번역하는 것은 어떨까요?

2022-09-09 06:49 UTC, Taeyoung96 commented
@spongebob03   
팀원들의 리뷰에 대해 업데이트 부탁드립니다. 😄

2022-09-09 10:07 UTC, spongebob03 commented
피드백 반영하여 번역 업데이트했습니다. 리뷰해주신 덕분에 수월하게 번역을 다듬을 수 있었습니다!

2022-09-12 08:04 UTC, Taeyoung96 approved these changes
매끄럽게 번역이 된 것 같습니다. 고생하셨습니다.

2022-09-12 09:31 UTC, codingbowoo requested changes
용어만 통일해주시면 머지 진행하겠습니다. 
허브 내에서는 번역할 거리가 꽤 많은 문서였네요. 기여에 감사드립니다!

2022-09-12 09:31 UTC, codingbowoo commented on pytorch_fairseq_translation.md
> +# 영어-러시아어 교차번역과 비교:
마찬가지로 교차 번역, 교차번역 중 하나로 통일해주시면 좋을 것 같습니다.

2022-09-13 12:44 UTC, codingbowoo approved these changes
LGTM! 가독성도 더 좋아졌네요. 기여에 감사드립니다.

2022-09-13 12:44 UTC, merged