SEMI-SUPERVISED AND SEMI-WEAKLY SUPERVISED IMAGENET MODELS 번역
PyTorchKorea/hub-kr pull request #92
Opened 2022-09-08 06:02 UTC by Woodywarhol9

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #61 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [x] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [x] 공식 허브의 내용을 반영하는 기여
- [x] 위 종류에 포함되지 않는 기여

## PR 설명
SEMI-SUPERVISED AND SEMI-WEAKLY SUPERVISED IMAGENET MODELS 번역

2022-09-08 06:03 UTC, Woodywarhol9 commented
Model Description 내용만 보고 이해가 잘 안되는 거 같아서 수정을 좀 했습니다!

2022-09-14 01:36 UTC, HyunKyungHan requested changes
깔끔한 번역인 것 같습니다! 
한 가지 수정 사항 제안 드립니다 :)

2022-09-14 01:36 UTC, HyunKyungHan commented on facebookresearch_semi-supervised-ImageNet1K-models_resnext.md
>  ### Model Description
다른 모델들 번역처럼 소제목도 번역하는 건 어떨까요?
`Model Description`을 `모델 설명`, 문서 하단의 `Citation`을 `인용`으로 번역하면 좋을 것 같습니다!

2022-09-14 05:39 UTC, Woodywarhol9 commented on facebookresearch_semi-supervised-ImageNet1K-models_resnext.md
>  ### Model Description
수정하겠습니다! 알려주셔서 감사합니다~

2023-04-02 04:14 UTC, hyoyoung approved these changes
good

2023-04-02 04:14 UTC, merged