ResNet50 번역
PyTorchKorea/hub-kr pull request #97
Opened 2022-09-10 07:19 UTC by cpprhtn

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/PyTorchKorea/hub-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #96 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 모델 소개를 번역하는 기여
- [ ] 공식 허브의 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
ResNet50 번역

2022-09-14 10:55 UTC, Woodywarhol9 reviewed
번역 잘 해주셨네요~
한 가지 수정 사항 제안 드려요!

2022-09-14 10:55 UTC, Woodywarhol9 commented on nvidia_deeplearningexamples_resnet50.md
> +이 모델은 Volta, Turing 및 NVIDIA Ampere GPU 아키텍처의 Tensor 코어를 사용하여 혼합 정밀도로 학습됩니다. 따라서 연구자들은 혼합 정밀 교육의 이점을 경험하면서 Tensor Core 없이 학습하는 것보다 2배 이상 빠른 결과를 얻을 수 있습니다. 이 모델은 시간이 지남에 따라 일관된 정확성과 성능을 보장하기 위해 각 NGC
`혼합 정밀도`는 `혼합 정밀도(mixed precision)`처럼 영어를 함께 적어주면 이해하기가 더 쉬울 거 같아요!

2022-09-14 11:59 UTC, cpprhtn commented on nvidia_deeplearningexamples_resnet50.md
> +이 모델은 Volta, Turing 및 NVIDIA Ampere GPU 아키텍처의 Tensor 코어를 사용하여 혼합 정밀도로 학습됩니다. 따라서 연구자들은 혼합 정밀 교육의 이점을 경험하면서 Tensor Core 없이 학습하는 것보다 2배 이상 빠른 결과를 얻을 수 있습니다. 이 모델은 시간이 지남에 따라 일관된 정확성과 성능을 보장하기 위해 각 NGC
감사합니다!

2023-04-02 04:16 UTC, hyoyoung requested changes
번역이 되어있는데 원문이 남아있는 경우가 있습니다
확인 후 정리 부탁드립니다

2023-04-02 06:20 UTC, cpprhtn commented
> 번역이 되어있는데 원문이 남아있는 경우가 있습니다 확인 후 정리 부탁드립니다


원문이랑 비교하면서 번역해두고 지우지를 않았네요.
감사합니다.

2023-04-02 14:56 UTC, hyoyoung approved these changes
good

2023-04-02 14:56 UTC, merged